---
# helm template --namespace=kube-system openstack-cloud-controller-manager -f apps/clouds/ovh-ccm/app/ovh-ccm-helm.yaml cpo/openstack-cloud-controller-manager > apps/clouds/ovh-ccm/app/ovh-ccm.yaml
#
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./ovh-ccm.yaml
