---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-operator
spec:
  interval: 48h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.48.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-helm
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    kubernetesServiceDnsDomain: ${CLUSTER_SUFFIX}
    priorityClassName: system-node-critical

    watchNamespaces: ["kafka"]
    watchAnyNamespace: false

    tmpDirSizeLimit: 100Mi
    extraEnvs:
      - name: JAVA_OPTS
        value: "-Xms256m -Xmx256m"

    dashboards:
      enabled: false
    rbac:
      create: yes
    serviceAccountCreate: yes
    serviceAccount: strimzi-cluster-operator

    resources:
      limits:
        memory: 768Mi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 100m

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    # nodeSelector:
    #   node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
