---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-replicator
spec:
  interval: 60h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: kubernetes-replicator
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    # priorityClassName:

    namespacesPrivileges:
      - get
      - watch
      - list

    replicationEnabled:
      secrets: true
      configMaps: true

      roles: false
      roleBindings: false
      serviceAccounts: false

      privileges:
        - get
        - watch
        - list
        - create
        - update
        - patch
        - delete

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 96Mi

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

  valuesFrom:
    - kind: ConfigMap
      name: kubernetes-replicator-helm-values
      optional: true
