---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hcloud-csi
  namespace: flux-system
spec:
  targetNamespace: csi-hcloud
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/clouds/hcloud-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
