---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app influxdb
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/monitoring/influxdb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
