---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: event-exporter
spec:
  interval: 60h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: kubernetes-event-exporter
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    fullnameOverride: event-exporter

    config:
      logLevel: error
      logFormat: json
      clusterName: ${CLUSTER_NAME}
      route:
        routes:
          - match:
              - receiver: "dump"
      receivers:
        - name: "dump"
          stdout: {}

    containerSecurityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault

    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
