---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app event-exporter
  namespace: flux-system
spec:
  targetNamespace: monitoring-events
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/logging/event-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: false
  interval: 72h
  retryInterval: 5m
