---
creation_rules:
  - path_regex: apps/flux-system/secrets/.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: age195etzk5xvqhr7jl7chpuq355er6ajejf5uvreqgj2aara2ymj9wqvv24am
    pgp: 349CAAD68AF02E2B
  - path_regex: secrets\..*\.yaml$
    age: age195etzk5xvqhr7jl7chpuq355er6ajejf5uvreqgj2aara2ymj9wqvv24am
    pgp: 349CAAD68AF02E2B
