global:
  leaderElection:
    namespace: "cert-manager"

crds:
  enabled: true
  keep: true

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

resources:
  requests:
    cpu: 10m
    memory: 32Mi

webhook:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

cainjector:
  enabled: true
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

startupapicheck:
  enabled: true
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule

revisionHistoryLimit: 2
