---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: cert-manager-helm-values
    files:
      - values.yaml=./helmvalues.yaml
