---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./helmrelease.yaml
  - ./cert-manager-issuer.yaml
configMapGenerator:
  - name: cert-manager-helm-values
    files:
      - values.yaml=./helmvalues.yaml
