---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile
helmDefaults:
  force: true
  recreatePods: true
  timeout: 600
  wait: true
  waitForJobs: true

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.15.3
    values: ["app/helmvalues.yaml"]
