---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app oracle-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  targetNamespace: csi-oci
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/clouds/oracle-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
