---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app proxmox-ccm
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/clouds/proxmox-ccm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 72h
  retryInterval: 1m
