---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prometheus-alertmanager
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/prometheus-alertmanager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: true
  interval: 30m
  retryInterval: 5m
