---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psmdb-operator
spec:
  interval: 48h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: psmdb-operator
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    watchAllNamespaces: true

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 2
      runAsGroup: 2
      fsGroup: 2
      fsGroupChangePolicy: "OnRootMismatch"

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
