---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app csi-autoresizer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  targetNamespace: csi-autoresizer
  path: ./apps/clouds/csi-autoresizer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 72h
  retryInterval: 5m
