---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app fluent-bit
  namespace: flux-system
spec:
  dependsOn:
    - name: fluentd-route
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/logging/fluent-bit/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: false
  interval: 72h
  retryInterval: 5m
