---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
spec:
  interval: 48h
  timeout: 10m

  maxHistory: 2

  chart:
    spec:
      chart: altinity-clickhouse-operator
      version: 0.25.6
      sourceRef:
        kind: HelmRepository
        name: clickhouse-operator
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: clickhouse-operator-helm-values
