---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 60m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: victoria-metrics
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-helm-values
  values:
    fullnameOverride: vm
    priorityClassName: system-cluster-critical

    # nodeSelector:
    #   node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
