---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 60m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: victoria-metrics
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-helm-values
  values:
    fullnameOverride: vm
    priorityClassName: system-cluster-critical

    vmAgent:
      secrets:
        - web-auth-tls
      externalLabels:
        cluster: ${CLUSTER_NAME}
      remoteWrite:
        - url: ${VM_REMOTEWRITE_URL}
          tlsConfig:
            certFile: /etc/vm/secrets/web-auth-tls/tls.crt
            keyFile: /etc/vm/secrets/web-auth-tls/tls.key
            serverName: monitoring.infra.betmaster.co
          inlineUrlRelabelConfig:
            - source_labels: ["__name__"]
              regex: nginx_ingress_controller_.*
              action: drop
            - source_labels: ["job"]
              regex: kubernetes-apiservers
              action: drop
            - source_labels: ["__name__"]
              regex: ^go_.*
              action: drop
            - action: replace
              targetLabel: cluster
              replacement: ${CLUSTER_NAME}

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
