---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app proxmox-csi
  namespace: flux-system
spec:
  targetNamespace: csi-proxmox
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/proxmox-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 30m
  retryInterval: 5m
