---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-actions-runner
  namespace: operator-gha
spec:
  interval: 60m

  targetNamespace: cicd
  storageNamespace: operator-gha

  maxHistory: 2
  driftDetection:
    mode: warn

  chart:
    spec:
      chart: github-actions-runner
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: Secret
      name: github-actions-runner-helm-values

  values:
    image:
      repository: ghcr.io/sergelogvinov/github-actions-runner
      tag: "2.325.0"

    controllerServiceAccount:
      name: arc
      namespace: operator-gha

    autoscaling:
      enabled: false
      minReplicas: 0
      maxReplicas: 3

    # runnerGroup: ""
    runnerScaleSetName: Builder

    githubConfigUrl: https://github.com/sergelogvinov/containers

    serviceAccount:
      create: false

    persistence:
      enabled: false
      storageClass: proxmox
      size: 10Gi

    dind:
      enabled: true
      resources:
        limits:
          cpu: 3
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 2Gi
      persistence:
        enabled: true
        annotations:
          resize.topolvm.io/increase: 10Gi
          resize.topolvm.io/storage_limit: 200Gi
          resize.topolvm.io/threshold: 15%
        storageClass: proxmox
        size: 50Gi

    mirrors:
      enabled: true
      persistence:
        enabled: false
        annotations:
          resize.topolvm.io/increase: 10Gi
          resize.topolvm.io/storage_limit: 200Gi
          resize.topolvm.io/threshold: 15%
        storageClass: proxmox
        size: 50Gi

    registry:
      enabled: false
      persistence:
        enabled: false
        annotations:
          resize.topolvm.io/increase: 10Gi
          resize.topolvm.io/storage_limit: 200Gi
          resize.topolvm.io/threshold: 15%
        storageClass: proxmox
        size: 50Gi

    metrics:
      enabled: false
