---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler-oci
  namespace: kube-system
spec:
  interval: 60h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.46.6
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: cluster-autoscaler-oracle-helm-values

  values:
    fullnameOverride: cluster-autoscaler-oci
    priorityClassName: system-cluster-critical

    image:
      repository: ghcr.io/sergelogvinov/cluster-autoscaler
      tag: "1.31"

    cloudProvider: oci
    cloudConfigPath: /etc/oci/config.ini

    extraArgs:
      cloud-config: /etc/oci/config.ini
      regional: true
      logtostderr: true
      stderrthreshold: info
      balance-similar-node-groups: true
      scan-interval: 15s
      scale-down-delay-after-add: 5m
      max-node-provision-time: 15m0s
      v: 4
    extraEnv:
      OCI_USE_INSTANCE_PRINCIPAL: "true"

    extraVolumeSecrets:
      cloud-config:
        name: oci-cloud-controller-manager
        mountPath: /etc/oci

    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
      node.cloudprovider.kubernetes.io/platform: oracle
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
