---
# kubectl kustomize --enable-helm apps/clouds/hcloud-csi/generate > apps/clouds/hcloud-csi/app/hcloud-csi.yaml
#
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: hcloud-csi
    valuesInline:
      storageClasses: []

      controller:
        priorityClassName: system-cluster-critical
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: node.cloudprovider.kubernetes.io/platform
                      operator: In
                      values:
                        - hcloud
                weight: 100
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
          - key: node.kubernetes.io/disk-pressure
            operator: Exists
            effect: NoSchedule

      node:
        priorityClassName: system-node-critical
        nodeSelector:
          node.cloudprovider.kubernetes.io/platform: hcloud
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
          - key: node.kubernetes.io/disk-pressure
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/unschedulable
            operator: Exists
            effect: NoSchedule

    releaseName: hcloud-csi
    version: 2.12.0
    repo: https://charts.hetzner.cloud
namespace: csi-hcloud
patches: []
