---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: alert-manager
  namespace: flux-system
spec:
  type: alertmanager
  address: http://prometheus-alertmanager.monitoring.svc:9093/api/v2/alerts/
