---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster-0/vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
