---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/flux-system
  - ./cluster-settings.yaml
  - ../../apps/cert-manager
  - ../../apps/metrics-server
  - ../../apps/proxmox-ccm
