---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./fluxcd.yaml
  - ./vars/cluster-settings.yaml
  # Flux components
  - ../../apps/flux-system
  # Kubernetes components
  - ../../apps/base/rbac
  - ../../apps/clouds/talos-upgrade-controller
  - ../../apps/base/cert-manager
  - ../../apps/base/metrics-server
  # Kubernetes ccm/csi
  - ../../apps/base/local-path-provisioner
  - ../../apps/clouds/proxmox-ccm
  - ../../apps/clouds/proxmox-csi
  # - ../../apps/clouds/csi-snapshotter
  - ../../apps/clouds/csi-autoresizer
  # Secrets
  - ../../apps/base/external-secrets
  # Logging
  - ../../apps/logging/fluentd-route
  - ../../apps/logging/fluent-bit
  # Monitoring
  - ../../apps/monitoring/victoria-metrics-operator
  - ../../apps/monitoring/victoria-metrics
  - ../../apps/monitoring/prometheus
  - ../../apps/monitoring/prometheus-alertmanager
  - ../../apps/monitoring/prometheus-node-exporter
  - ../../apps/monitoring/grafana
  # Ingress
  - ../../apps/ingress/ingress-nginx
  - ../../apps/ingress/ingress-skipper
  # Apps
  - ../../apps/cicd/gha-actions-runner
  - ../../apps/cicd/teamcity
