---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/flux-system
  - ./cluster-settings.yaml
  # Kubernetes components
  - ../../apps/cert-manager
  - ../../apps/metrics-server
  - ../../apps/local-path-provisioner
  - ../../apps/proxmox-ccm
  # Logging
  - ../../apps/fluentd-route
  - ../../apps/fluent-bit
  # Monitoring
  - ../../apps/victoria-metrics-operator
  - ../../apps/victoria-metrics
  - ../../apps/prometheus
  # - ../../apps/prometheus-alertmanager
