apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: cloud-controller-manager-scaleway
  name: cloud-controller-manager-scaleway
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    component: cloud-controller-manager-scaleway
  name: system:cloud-controller-manager-scaleway
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cloud-controller-manager-scaleway
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    component: cloud-controller-manager-scaleway
  name: system:cloud-controller-manager-scaleway
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager-scaleway
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: cloud-controller-manager-scaleway
  name: system:cloud-controller-manager-scaleway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cloud-controller-manager-scaleway
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager-scaleway
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: cloud-controller-manager-scaleway
  name: cloud-controller-manager-scaleway
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: scaleway-cloud-controller-manager
      component: cloud-controller-manager-scaleway
  template:
    metadata:
      labels:
        app: scaleway-cloud-controller-manager
        component: cloud-controller-manager-scaleway
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node.cloudprovider.kubernetes.io/platform
                operator: In
                values:
                - scaleway
            weight: 100
      containers:
      - args:
        - -v=2
        - --cloud-provider=scaleway
        - --controllers=cloud-node-lifecycle
        - --leader-elect-resource-name=cloud-controller-manager-scaleway
        - --allow-untagged-cloud
        - --secure-port=10258
        envFrom:
        - secretRef:
            name: scaleway-secret
        image: ghcr.io/sergelogvinov/cloud-controller-manager-scaleway:1.31
        imagePullPolicy: Always
        name: scaleway-cloud-controller-manager
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
      dnsPolicy: Default
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: ""
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65521
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cloud-controller-manager-scaleway
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
