---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-metrics
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/victoria-metrics/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 30m
  retryInterval: 5m
