---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app talos-upgrade-controller
  namespace: flux-system
spec:
  targetNamespace: operator-talos
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/talos-upgrade-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: true
  interval: 30m
  retryInterval: 5m
