---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app local-path-provisioner
  namespace: flux-system
spec:
  targetNamespace: csi-local-path
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/local-path-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 30m
  retryInterval: 5m
