---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile
helmDefaults:
  force: true
  recreatePods: true
  timeout: 600
  wait: true
  waitForJobs: true

repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

releases:
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    values: ["app/helmvalues.yaml"]
