---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 168h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    # ghcr.io/fluxcd/flux-manifests:v2.8.1
    digest: sha256:45ed09e8241e4b0ee38d0fc8d8e42b6002d55c880b0859c9c484bf22340116d5
