---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 168h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    # tag: v2.5.1
    digest: sha256:8a1b40166d6b9575d8ba3987bca8d8cec629c4510cd2b4706bd005c4421b9cf6
