---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 168h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    digest: sha256:57804ca34eab87a2071ec03c4a523e89e1c8775937586ba89fc6c66148700f02
