---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 168h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    # ghcr.io/fluxcd/flux-manifests:v2.7.3
    digest: sha256:b0f84f773fa28d9bbc2dbbf8fa45e9950b41cc2b6825df8054d5d2936e231da7
