---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 48h
  type: oci
  url: oci://ghcr.io/prometheus-community/charts
