---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sergelogvinov
  namespace: flux-system
spec:
  interval: 60m
  type: oci
  url: oci://ghcr.io/sergelogvinov/charts
