---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teamcity
spec:
  interval: 60m
  timeout: 30m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: teamcity
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: teamcity-helm-values
    - kind: Secret
      name: teamcity-helm-values
      optional: true

  values:
    server:
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi

    agent:
      resources:
        limits:
          cpu: 2
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi

    dind:
      resources:
        limits:
          cpu: 2
          memory: 16Gi
        requests:
          cpu: 500m
          memory: 2Gi
