server:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  # nodeSelector:
  #   kubernetes.io/role: builder
  persistentVolume:
    enabled: true
    annotations:
      resize.topolvm.io/increase: 10Gi
      resize.topolvm.io/storage_limit: 100Gi
      resize.topolvm.io/threshold: 15%
    storageClass: proxmox
    size: 20Gi

agent:
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  # nodeSelector:
  #   kubernetes.io/role: builder

dind:
  resources:
    limits:
      cpu: 2
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 2Gi

  persistence:
    enabled: true
    annotations:
      resize.topolvm.io/increase: 10Gi
      resize.topolvm.io/storage_limit: 100Gi
      resize.topolvm.io/threshold: 15%
    storageClass: proxmox
    size: 10Gi

metrics:
  enabled: true
