---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teamcity-db
spec:
  interval: 72h

  maxHistory: 2
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: StatefulSet

  chart:
    spec:
      chart: postgresql-single
      version: 1.10.5
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    fullnameOverride: teamcity-db
    replicaCount: 1

    image:
      tag: "16.11"

    priorityClassName: production-db
    podlabels:
      project: db
      severity: critical

    initdb:
      database: teamcity
      username: teamcity

    pgHbaConfiguration:
      # host    database    user                  address       auth-method
      #
      - host    teamcity    teamcity              10.0.0.0/8    scram-sha-256
      - hostssl teamcity    teamcity              10.0.0.0/8    scram-sha-256

    postgresqlServerMemory: 512
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

  valuesFrom:
    - kind: ConfigMap
      name: teamcity-db-helm-values
    - kind: Secret
      name: teamcity-db-helm-values
      optional: true
