---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clickhouse-operator
  namespace: flux-system
spec:
  interval: 48h
  url: https://docs.altinity.com/clickhouse-operator/
