---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app clickhouse-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
    - name: cert-manager
  targetNamespace: operator-clickhouse
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/database/clickhouse-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
