---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-clusters
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/sergelogvinov/gitops.git
  secretRef:
    name: github-token
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/apps
    !/clusters
  verify:
    mode: HEAD
    secretRef:
      name: github-pgp-public-keys
