---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-upgrade-controller
spec:
  interval: 60h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: system-upgrade-controller
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    talosVersion: ${TALOS_VERSION}
    plan:
      kubernetes:
        enabled: true
        version: ${KUBERNETES_VERSION}
