---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app psmdb-operator
  namespace: flux-system
spec:
  targetNamespace: operator-psmdb
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/database/psmdb-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
