---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-actions-runner
  namespace: operator-gha
spec:
  interval: 60m
  timeout: 10m

  targetNamespace: cicd
  storageNamespace: operator-gha

  maxHistory: 2
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: StatefulSet

  chart:
    spec:
      chart: github-actions-runner
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: github-actions-runner-helm-values
    - kind: Secret
      name: github-actions-runner-helm-values

  values:
    fullnameOverride: github-actions-runner

    image:
      repository: ghcr.io/sergelogvinov/github-actions-runner
      tag: "2.327.1-gcp"

    controllerServiceAccount:
      name: arc
      namespace: operator-gha

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 16

    # runnerScaleSetName: deploy

    serviceAccount:
      create: true
