replicaCount: 1

volumeSnapshotClasses: []
storageClasses: []

controller:
  scaleway:
    existingSecretName: "scaleway-csi-secret"

  driver:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
  provisioner:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
  attacher:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
  resizer:
    resources:
      requests:
        cpu: 10m
        memory: 24Mi
  liveness:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi

  migration:
    enabled: false
  snapshotter:
    enabled: false
  snapshotController:
    enabled: false
  webhook:
    enabled: false

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule

node:
  driver:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
  registrar:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
  liveness:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi

  nodeSelector:
    node.cloudprovider.kubernetes.io/platform: scaleway
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
    - key: node.kubernetes.io/unschedulable
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
