---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scaleway-csi
spec:
  interval: 60h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: scaleway-csi
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: scaleway
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    node:
      driver:
        image:
          # containerd-2.0 bugfix
          repository: ghcr.io/sergelogvinov/scaleway-csi
          tag: v0.3.3

  valuesFrom:
    - kind: ConfigMap
      name: scaleway-csi-helm-values
    - kind: Secret
      name: scaleway-csi-helm-values
      optional: true
