---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-alertmanager
spec:
  interval: 60m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: alertmanager
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: prometheus-alertmanager-helm-values
