---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: external-dns
  path: ./apps/base/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
