---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-plugin-wal-g
spec:
  interval: 48h
  timeout: 10m

  maxHistory: 2

  chart:
    spec:
      chart: cnpg-plugin-wal-g
      version: 0.2.2-helm-chart
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-plugin-wal-g
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    fullnameOverride: cloudnative-pg-plugin-wal-g

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi

    nodeSelector:
      kubernetes.io/arch: amd64
      # node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
