---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 48h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    priorityClassName: production-db

    config:
      data:
        CERTIFICATE_DURATION: "180"
        KUBERNETES_CLUSTER_DOMAIN: ${CLUSTER_SUFFIX}
        # There is no way to disable unschedulable nodes to switchover
        DRAIN_TAINTS: "node.kubernetes.io/unschedulable,ToBeDeletedByClusterAutoscaler,karpenter.sh/disrupted,karpenter.sh/disruption"

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
