---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-local
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: ./apps/base/coredns-local/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: false
  interval: 72h
  retryInterval: 5m
