fullnameOverride: prometheus-kube-state-metrics
priorityClassName: system-cluster-critical

service:
  annotations:
    prometheus.io/port: "8080"

resources:
  limits:
    memory: 256Mi
    cpu: 100m
  requests:
    memory: 50Mi
    cpu: 50m

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
