---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gha-runner-scale-set-controller
  namespace: flux-system
spec:
  targetNamespace: operator-gha
  path: ./apps/cicd/gha-actions-runner/gha-runner-scale-set-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 72h
  retryInterval: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gha-runner-scale-set
  namespace: flux-system
spec:
  dependsOn:
    - name: gha-runner-scale-set-controller
  targetNamespace: operator-gha
  path: ./apps/cicd/gha-actions-runner/gha-runner-scale-set
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 12h
  retryInterval: 5m
