---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-plugin-wal-g
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
    - name: cert-manager
    - name: cloudnative-pg
  targetNamespace: operator-cnpg
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/database/cloudnative-pg-plugin/wal-g
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
