---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: operator-cnpg
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/database/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 30m
  retryInterval: 5m
