apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ha9DvTPg9mT3S+mfGN+EGHFOWn+BWQSY4ieATTrszf8XnZ/zscHNaUW3lY78Iii3gL9Fx8WNulqRLXAVZXL2kssdqjPDb6+3uK7FFzQf56R+l0QZlZ2s8tchi8m1yjznLOFYRar7sZYIC1IYXInk2wadreBtuFJezQ==,iv:yBtNCEgU0XAMAu6pXH/crga48xVSra+vt0DtqpxBV4k=,tag:Nlvq8TxR///2KvLJxZNgLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age195etzk5xvqhr7jl7chpuq355er6ajejf5uvreqgj2aara2ymj9wqvv24am
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TjJBczFTOEFPbEQ5QVpI
            S2JXMmY4UnpCN1pyQng2YjFjNEt4T3IzbG1jClhMUk1OcCtFUXNTVk1IbEl4SHRQ
            OTh6ODF0UzgvNnhybk9uRkFUQk9ER3cKLS0tIDlOTkJUVnVjVlZ3S1JOcEM4a1RL
            dmdWUW5XMEtrVmRpNWdlTmk0ZEM0dTAKfuEP/YZeKKSC31NOXuSgpOpvYp/SCEI5
            MuYE4jw+y5BAiP+iyPBrQmRFGquIPlMrvgV4yPuMp1yNHb8Tc7JAqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T11:41:55Z"
    mac: ENC[AES256_GCM,data:Duczi/VrR30/xidFXykr/LTAriFgbLHhN8QuGvlbq0TzBKrh8Za5HmFVbrm1aJaQ7obwo1DXR0pMqkvjzsU0r79Yn8/SXszmgPGG5rIOk7ZvQHmoLslsgbdrNVIlfBH8kV5Riu47yQSQnB4u8/aXd7m3LbhYQZPbLTD0odDbQn0=,iv:qax+TRYmLadwtfgi1uCw6HRH2uPw8HDtZpMVD9fLwpQ=,tag:MXxkpiKuu9LbQlrA8a4B1g==,type:str]
    pgp:
        - created_at: "2024-11-17T11:41:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5SeLKJj2tCjARAAjy+HXTAy6HQ7m57ipTwkZYVsyD9TMyUO6iMQl0ThznrX
            iaYLGqSRIm3RGibsKL+L1BZ22yX0ZxF7cu9+cH7jNr7wJvWS/cUJQZtlCIR4Afi2
            Sj6yc5VdFH40xWBdEeuTZKCjGRYTfAfJ1jFDdB6BtuuWxGQgBmQEtuPfb+uyZLpF
            VLRCei5CARtBg0Lha816NlQzMJX7e1TN47Xeulgz++4qoK2ZdOkhmQ6F0SCmqWT6
            dIwJEULYB9mzepHe1ZCrmxC3nFPeG22kPBe37tNCFJModyPHvel+5W/4KHIL3v3p
            yV21s74EWjDJnO1Qb8CFer00tMg4MUyaQJO3lPZeZ91+nItzgbv7BulyJOVQcMOI
            fuJKwXPrMQYtOZmDOboGE0x6GoSv7M7fZvCRMP1LjXARQLs8K5e6rV82yR4X3V6n
            j3g0yubQ1ljPHI77rJveJ1RkxanPk6/dcwQr6nU0zQtmS8BEQ+5zK6JSc1PnQspY
            eKeAP4eBiiYtkCEc+ykNEWzkWMC0jYAnLA22P4mkeuFfvCyamtqJpvENrhiOF4KE
            A1IZIrgyk4Pp1NaauQk26T3EVECTq9rZvZ+eLpPP9Is3NR1O7a/EIn8/xNn1NFy2
            lQtkMALdxkEeeKeFvWJNeQS+e2OyRSv+u5QeGOm/e/evmzodZ3GtplmZCt4FfAbS
            XgEV7bvDI2LCwtt8DE0gvraxrcX6cW8LYexOH57hR3neJPeO+UjNiHKOz+OFWOWT
            Kkb3Xl+bUEJ/3/8VhCYW7+F5VqEMniLWQTRv46EdgizYQl+COyEncrLZLxII97I=
            =X193
            -----END PGP MESSAGE-----
          fp: 349CAAD68AF02E2B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
