---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-cloud-controller-manager
spec:
  interval: 60h

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: talos-cloud-controller-manager
      version: 0.4.6
      sourceRef:
        kind: HelmRepository
        name: siderolabs
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    service:
      containerPort: 50258
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "https"
        prometheus.io/port: "50258"

    logVerbosityLevel: 4

    daemonSet:
      enabled: true

    tolerations:
      - effect: NoSchedule
        operator: Exists

  valuesFrom:
    - kind: ConfigMap
      name: talos-cloud-controller-manager-helm-values
