---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app keda
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
    - name: cert-manager
  targetNamespace: keda
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/base/keda/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: false
  interval: 72h
  retryInterval: 5m
