---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prometheus
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/monitoring/prometheus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
