---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hybrid-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  targetNamespace: csi-hybrid
  path: ./apps/base/hybrid-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 72h
  retryInterval: 5m
