controller:
  kind: DaemonSet
  allowSnippetAnnotations: "true"

  hostNetwork: true
  hostPort:
    enabled: false
    ports:
      http: 80
      https: 443

  dnsPolicy: ClusterFirstWithHostNet

  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  priorityClassName: system-node-critical

  publishService:
    enabled: false

  config:
    worker-processes: "auto"
    worker-cpu-affinity: "auto"
    error-log-level: "error"

    server-tokens: "false"
    http-redirect-code: "301"

    brotli-level: "6"
    brotli-types: text/xml image/svg+xml application/x-font-ttf image/vnd.microsoft.icon application/x-font-opentype application/json font/eot application/vnd.ms-fontobject application/javascript font/otf application/xml application/xhtml+xml text/javascript application/x-javascript text/plain application/x-font-truetype application/xml+rss image/x-icon font/opentype text/css image/x-win-bitmap
    enable-brotli: "true"

    use-gzip: "true"
    use-geoip2: "false"

    use-forwarded-headers: "true"
    # curl https://www.cloudflare.com/ips-v4 2>/dev/null | tr '\n' ','
    proxy-real-ip-cidr: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,10.108.0.0/14"

    enable-access-log-for-default-backend: "true"
    log-format-escape-json: "true"
    log-format-upstream: '{"ip":"$remote_addr", "geo":"$http_cf_ipcountry", "ssl":"$ssl_protocol", "method":"$request_method", "proto":"$scheme", "host":"$host", "uri":"$request_uri", "status":$status, "size":$bytes_sent, "agent":"$http_user_agent", "req_time":$request_time, "res_time":"$upstream_response_time", "cache":"$upstream_cache_status", "referer":"$http_referer", "namespace":"$namespace"}'

    upstream-keepalive-connections: "32"
    proxy-connect-timeout: "10"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
    # for Sentry
    proxy-buffer-size: "16k"

    ssl-protocols: "TLSv1.2 TLSv1.3"
    ssl-ecdh-curve: "prime256v1:secp384r1"

    hsts: "true"
    hsts-max-age: "31536000"
    hsts-include-subdomains: "true"
    hsts-preload: "true"
    proxy-hide-headers: "strict-transport-security"
    proxy-headers-hash-bucket-size: "128"

    server-name-hash-bucket-size: "64"
    server-name-hash-max-size: "512"

    limit-req-status-code: "429"

    client-header-timeout: "30"
    client-body-timeout: "30"

  minReadySeconds: 15

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"

  extraArgs:
    default-ssl-certificate: "ingress-nginx/default-tls"
    update-status: "false"
    post-shutdown-grace-period: 60

  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
  readinessProbe:
    periodSeconds: 30

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector:
    node-role.kubernetes.io/web: ""

  service:
    enabled: true
    type: ClusterIP
    clusterIP: None
    ipFamilyPolicy: "RequireDualStack"
    ipFamilies:
      - IPv4
      - IPv6

  admissionWebhooks:
    enabled: false
  metrics:
    enabled: true

revisionHistoryLimit: 2

defaultBackend:
  enabled: false
