---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 60h
  timeout: 30m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-helm-values
    - kind: Secret
      name: ingress-nginx-helm-values
      optional: true
