---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app loki
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  targetNamespace: logs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/logging/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: true
  interval: 1h
  retryInterval: 5m
