---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teamcity
  namespace: flux-system
spec:
  targetNamespace: cicd
  path: ./apps/cicd/teamcity/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 60m
  retryInterval: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teamcity-db
  namespace: flux-system
spec:
  targetNamespace: cicd
  path: ./apps/cicd/teamcity/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 60m
  retryInterval: 5m
