---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app teamcity
  namespace: flux-system
spec:
  targetNamespace: cicd
  path: ./apps/cicd/teamcity/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: false
  interval: 30m
  retryInterval: 5m
