---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app skipper
  namespace: flux-system
spec:
  targetNamespace: ingress-skipper
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
  path: ./apps/ingress/skipper/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  wait: true
  interval: 30m
  retryInterval: 5m
