---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-system
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/flux-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      # - kind: Secret
      #   name: cluster-secrets
  wait: true
  interval: 30m
