---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./vmsingle.yaml
  - ./vmagent.yaml
  - ./vmalert.yaml
  - ../config
