---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
spec:
  interval: 60m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: keda
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    priorityClassName: system-node-critical

    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
