---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-skipper
spec:
  interval: 60m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: skipper
      version: 0.2.16
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: ingress-skipper-helm-values
