---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app azure-csi
  namespace: flux-system
spec:
  targetNamespace: csi-azure
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./apps/clouds/azure-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-clusters
  wait: true
  interval: 30m
  retryInterval: 5m
