name: Release please

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Do not create a new release PR for changes pushed by the GitHub Actions bot.
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create release PR
        id: release
        uses: googleapis/release-please-action@v5
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
