name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 03:00 UTC

jobs:
  renovate:
    name: "Renovate"
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
      security-events: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4

      - name: Renovate
        uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        with:
          configurationFile: .github/renovate-global.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
