name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 03:00 UTC

jobs:
  renovate:
    name: "Renovate"
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
      security-events: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Renovate
        uses: renovatebot/github-action@3633cede7d4d4598438e654eac4a695e46004420 # v46.1.7
        with:
          configurationFile: .github/renovate-global.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
