---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: "cluster-0.sinextra.dev"
  CLUSTER_NAME: "Cluster-0"
  CLUSTER_EMAIL: "cluster@sinextra.dev"
  CLUSTER_INGRESS_CLASS: "nginx"
  CLUSTER_INGRESS_DOMAIN: "hello.com"

  # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
  TALOS_VERSION: "v1.8.3"
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  KUBERNETES_VERSION: "v1.31.2"
