---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: "cluster-0.sinextra.dev"
  CLUSTER_NAME: "Cluster-0"
  CLUSTER_EMAIL: "cluster@sinextra.dev"
