apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-ssd
  annotations:
    resize.topolvm.io/enabled: "true"
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  csi.storage.k8s.io/fstype: xfs
  replication-type: none
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-balanced
  annotations:
    resize.topolvm.io/enabled: "true"
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: xfs
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-standard
  annotations:
    resize.topolvm.io/enabled: "true"
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-standard
  csi.storage.k8s.io/fstype: xfs
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
