apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovh-hdd
  annotations:
    resize.topolvm.io/enabled: "true"
provisioner: cinder.csi.openstack.org
parameters:
  type: classic
  availability: nova
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovh-ssd
  annotations:
    resize.topolvm.io/enabled: "true"
provisioner: cinder.csi.openstack.org
parameters:
  type: high-speed
  availability: nova
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovh-ssd-gen2
  annotations:
    resize.topolvm.io/enabled: "true"
provisioner: cinder.csi.openstack.org
parameters:
  type: high-speed-gen2
  availability: nova
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
