---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./secrets.fluxcd.yaml
  - ./secrets.discord.yaml
  - ./cluster-settings.yaml
  # - ./cluster-secrets.yaml
  # - ./cluster-azure.yaml
  # - ./cluster-gcp.yaml
  - ./priorityclass.yaml
  # - ./secrets.openstack-csi.yaml
  # - ./secrets.gcpsm-csi.yaml
  # - ./secrets.gcpsm-autoscaler.yaml
  - ./csi-azure.yaml
  - ./csi-gcp.yaml
  - ./csi-ovh.yaml
  - ./csi-proxmox.yaml
  # - ./secrets.ingress-nginx-dhparam.yaml
  # - ./secrets.external-secrets.yaml
  # - ./secrets.cloudflare.yaml
  # - ./secrets.helm-sa.yaml
  # - ./secrets.gcpsm-secret.yaml
configMapGenerator:
  - name: prometheus-alertmanager-route-helm-values
    namespace: monitoring
    files:
      - values.yaml=./prometheus-alertmanager.yaml
  - name: cluster-autoscaler-gcp-helm-values
    namespace: kube-system
    files:
      - values.yaml=./cluster-autoscaler-gcp.yaml
  - name: cluster-autoscaler-azure-helm-values
    namespace: kube-system
    files:
      - values.yaml=./cluster-autoscaler-azure.yaml
secretGenerator:
  - name: rbac-common-helm-values
    namespace: kube-system
    files:
      - values.yaml=./cluster-rbac.yaml
  - name: fluentd-route-helm-values
    namespace: kube-system
    files:
      - values.yaml=./fluentd-route.yaml
  # - name: talos-backup-helm-values
  #   namespace: operator-talos
  #   files:
  #     - values.yaml=./secrets.talos-backup.yaml
  - name: proxmox-ccm-plugin-helm-values
    namespace: kube-system
    files:
      - values.yaml=./secrets.proxmox.yaml
  - name: proxmox-csi-plugin-helm-values
    namespace: csi-proxmox
    files:
      - values.yaml=./secrets.proxmox.yaml

  - name: prometheus-alertmanager-helm-values
    namespace: monitoring
    files:
      - values.yaml=./secrets.prometheus-alertmanager.yaml
  - name: grafana-helm-values
    namespace: monitoring
    files:
      - values.yaml=./secrets.grafana.yaml

  # - name: ingress-nginx-helm-values
  #   namespace: ingress-nginx
  #   files:
  #     - values.yaml=./ingress-nginx.yaml

  - name: github-actions-runner-helm-values
    namespace: operator-gha
    files:
      - values.yaml=./secrets.github-actions-runner.yaml
