---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./cluster-settings.yaml
  - ./priorityclass.yaml
  - ./proxmox-storage.yaml
configMapGenerator:
  - name: prometheus-alertmanager-route-helm-values
    namespace: monitoring
    files:
      - values.yaml=./prometheus-alertmanager.yaml
secretGenerator:
  - name: rbac-common-helm-values
    namespace: kube-system
    files:
      - values.yaml=./cluster-rbac.yaml
  - name: prometheus-alertmanager-helm-values
    namespace: monitoring
    files:
      - values.yaml=./secrets.prometheus-alertmanager.yaml
  - name: proxmox-csi-plugin-helm-values
    namespace: csi-proxmox
    files:
      - values.yaml=./secrets.proxmox.yaml
  - name: github-actions-runner-helm-values
    namespace: operator-gha
    files:
      - values.yaml=./secrets.github-actions-runner.yaml
