apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox
provisioner: csi.proxmox.sinextra.dev
parameters:
  storage: system
  cache: directsync
  csi.storage.k8s.io/fstype: xfs
  ssd: "true"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
