apiVersion: ENC[AES256_GCM,data:+RM=,iv:/ddfUG1wC0G8V/hAhuP9heFLMRYJ1WoCvg1J7eUtio4=,tag:8J68NFtCGBKkb4et5N6uQA==,type:str]
kind: ENC[AES256_GCM,data:qXDqhwxz,iv:eSEAXtigkgPoT2G3PlpLNZxRRdYoAhEMep4dCH7goQg=,tag:jRjVM+1dNVB23wJT2Ia0/w==,type:str]
metadata:
  name: ENC[AES256_GCM,data:azknE9q64Us4Y067,iv:dzHGqYx3AWj2ztHQcS/aHQyiN53YRByLJxMfSwc9eXQ=,tag:D3si+MwHbJFz6YnnjX8QGw==,type:str]
  namespace: ENC[AES256_GCM,data:ABdNUEM0Ghf2LzM=,iv:TZqvQ2Tz/NNiHxmRD3dpdsymg+h9Eljg404Gy6UC/Xc=,tag:WrVaXvzK+MRhgXYJ0y0mAQ==,type:str]
stringData:
  password: ENC[AES256_GCM,data:SnVo6sjNsk3+Lvs2B6OrBIP1RRmkNGycZZJSULsik44PQGq+RDHUuzuxTV/ofuf9gXaN3CB/rgQUDuXH6dr3nxf6UyVs3cj43YBP2PyTuJj6P7RUJwcaXdpGatkf,iv:5AaF5LCVfXXiGQVlwfPWFnvgazMC/tVXxFmPkXxeIPw=,tag:zN7PVzPuOMCgiibjEFOL3g==,type:str]
  username: ENC[AES256_GCM,data:M4rS,iv:UOYB05OAeHWS30Q/Oo4pM8hFfvcNlt2Z+sYyuDB/Q0o=,tag:K1LNtitrcphrSonFL3dSpQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0L1dtRTVwSUg0RSswYkx2
        SXdmWnQyQ2IrSERPTmJaZ0x3K21zVlRVRlNnCmhnZGdQVkoyRHhZSjkvd01PWDRI
        cEt3MDJkUzFrdVlnQlR5b293QVJuaVkKLS0tIFhmeFhPbGRUMFd5MmFOSmNZT256
        akdJaWliMFo0eXdlQk5DbFpPb3c0c00Ko4ZVKybyuoNGdM/YwjLVYpl4972rf2yD
        x+d44haitgY7bm7K8zX2Pw6lUbYXv3Tm9QS6CrVDXuju8BD3FZpF+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195etzk5xvqhr7jl7chpuq355er6ajejf5uvreqgj2aara2ymj9wqvv24am
  lastmodified: "2026-08-24T04:12:00Z"
  mac: ENC[AES256_GCM,data:aGaCJAR9FPNYVCyKR7WMndJOW9bAiudGYeP0/MPes+GJKwRTV/9yYEplPPDsIpqslBSqdwA0xDeQKu5Ngmr3yszC5uquT+e4h/WLjbonROnyVs6F3lHl/0RRVZkep3oJ236CGkTBndhe8mAAvfZtX1JEYHLKVhzkZhCGGTjZZbc=,iv:WKCS19Qh6kMktcDSj6nkIVWsBd9mftnUSOVCZe35CV8=,tag:FalMvgvXbeYa0SNdyiuVrQ==,type:str]
  pgp:
    - created_at: "2026-08-24T04:12:00Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5SeLKJj2tCjAQ//VJdOpUFWANaG9uKLncVNSAO0cSfX5Yj4J5g+46NNkAOz
        Jyy1FPmEGez28Ff0H9hkbF2YnQpuN/5uyM0au/vph19j2JTw7sb4R0cgccze0ysI
        4L3nbBhbozETffIT3wLy/BKtgW/i+lscoErKZml8qLSn2IeW4xdiK5khSlFduxV2
        4XfhQnXhFv82OQOW/Rl0zQJscWY2+my1uzb20jElJ9rG3A5/E0nmPsifNRXKURPq
        tym8u+qcYZ/vTbSvRKF2z5DkaEGW4eg52KHOZDu45FTd6F1QYJwageN0GSfX1758
        We+2owdEFQkRTFrh41X9b9m9gNbHchKhlgTE5siymeDVMtI8qGzqRBDpjn5DZO3v
        GhzBxWdFW+31QAozw0WEr0Thlgt9Br307+6SSp77kz3pKTMTVVslCuAO008Acklh
        O/nocNimSTINNDLEdPIp+MzdH9cepPlLiH7d3MZjMI8vumr8rvMtw7zEeGAIGOT3
        +EykATKc4Z3Wg05dfPpOspDrt+emoJ2z0WfGYvYU2xIx7RZW2VKXSbUWNAcUe4rS
        XUZqEYwt9PAwuT0YQds0VYN77HRMKaUg3lBxNFH5OyDEsk1bU4Dx7zF11dzgJ6Bb
        vhL4WNwXkMuOZNYiSGPQtkLiSSSZuAVbM/nS5y5UYk5yNhstyVl3PTx/F6iRXwPS
        XgH/8AHkMhKFPGAw5XUE5f7JSJ3NJlCNicVbDErU+WzohYDtqVBDblyWYuDNskGV
        BXADNlW5FKXrZH0fq4pZp/0+/7WXTyWPSCta+sUNMW2tDl0QYaRT9/hSbEoyKtc=
        =hzF9
        -----END PGP MESSAGE-----
      fp: 349CAAD68AF02E2B
  unencrypted_suffix: _unencrypted
  version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:Q3g=,iv:y4O06CEKzylwWPQz7px1An1KpZ/pM2ee7rpbSNYHvRM=,tag:gYDgUDvoUoVtSlSsDnWLIQ==,type:str]
kind: ENC[AES256_GCM,data:uiVjwkNt,iv:je4KP94nJYtsTAV2LdDZ7e6x9+3SQ64zKXnzdBIec10=,tag:Gp6LvgOG5GX+NXbvHdbxuw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:k/ZRIpdsp0c=,iv:zJs2VM7nHgoElc1PZrPnCb9gbR9i9LB63gLmCMwEpqY=,tag:32xyYGdLtaA85isn+diN9Q==,type:str]
  namespace: ENC[AES256_GCM,data:hFr0x93lGW/e2tI=,iv:B+ycQgmLCpoFodWIhCIQuA/RpQFH4CY72OZRXmrd2q4=,tag:nHsBQiRK64VL7toyPFEVFg==,type:str]
stringData:
  age.agekey: ENC[AES256_GCM,data:ZJfNUDis2ZOYtweU9c3lbP8ENZ+Dk+x0Ag4mI/Wg+9Zizm5+luSowmvKt+TOr04J+RWTF4/nSWD4D87U+nTUe2Y9qgiy6TKGRLU=,iv:3vzSIEBUbfaYSIOwe8hLJOIA4Erykw8XUgAGpVpsrjM=,tag:w1FdY5UTgzT3DKvct8D23Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0L1dtRTVwSUg0RSswYkx2
        SXdmWnQyQ2IrSERPTmJaZ0x3K21zVlRVRlNnCmhnZGdQVkoyRHhZSjkvd01PWDRI
        cEt3MDJkUzFrdVlnQlR5b293QVJuaVkKLS0tIFhmeFhPbGRUMFd5MmFOSmNZT256
        akdJaWliMFo0eXdlQk5DbFpPb3c0c00Ko4ZVKybyuoNGdM/YwjLVYpl4972rf2yD
        x+d44haitgY7bm7K8zX2Pw6lUbYXv3Tm9QS6CrVDXuju8BD3FZpF+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195etzk5xvqhr7jl7chpuq355er6ajejf5uvreqgj2aara2ymj9wqvv24am
  lastmodified: "2026-08-24T04:12:00Z"
  mac: ENC[AES256_GCM,data:aGaCJAR9FPNYVCyKR7WMndJOW9bAiudGYeP0/MPes+GJKwRTV/9yYEplPPDsIpqslBSqdwA0xDeQKu5Ngmr3yszC5uquT+e4h/WLjbonROnyVs6F3lHl/0RRVZkep3oJ236CGkTBndhe8mAAvfZtX1JEYHLKVhzkZhCGGTjZZbc=,iv:WKCS19Qh6kMktcDSj6nkIVWsBd9mftnUSOVCZe35CV8=,tag:FalMvgvXbeYa0SNdyiuVrQ==,type:str]
  pgp:
    - created_at: "2026-08-24T04:12:00Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5SeLKJj2tCjAQ//VJdOpUFWANaG9uKLncVNSAO0cSfX5Yj4J5g+46NNkAOz
        Jyy1FPmEGez28Ff0H9hkbF2YnQpuN/5uyM0au/vph19j2JTw7sb4R0cgccze0ysI
        4L3nbBhbozETffIT3wLy/BKtgW/i+lscoErKZml8qLSn2IeW4xdiK5khSlFduxV2
        4XfhQnXhFv82OQOW/Rl0zQJscWY2+my1uzb20jElJ9rG3A5/E0nmPsifNRXKURPq
        tym8u+qcYZ/vTbSvRKF2z5DkaEGW4eg52KHOZDu45FTd6F1QYJwageN0GSfX1758
        We+2owdEFQkRTFrh41X9b9m9gNbHchKhlgTE5siymeDVMtI8qGzqRBDpjn5DZO3v
        GhzBxWdFW+31QAozw0WEr0Thlgt9Br307+6SSp77kz3pKTMTVVslCuAO008Acklh
        O/nocNimSTINNDLEdPIp+MzdH9cepPlLiH7d3MZjMI8vumr8rvMtw7zEeGAIGOT3
        +EykATKc4Z3Wg05dfPpOspDrt+emoJ2z0WfGYvYU2xIx7RZW2VKXSbUWNAcUe4rS
        XUZqEYwt9PAwuT0YQds0VYN77HRMKaUg3lBxNFH5OyDEsk1bU4Dx7zF11dzgJ6Bb
        vhL4WNwXkMuOZNYiSGPQtkLiSSSZuAVbM/nS5y5UYk5yNhstyVl3PTx/F6iRXwPS
        XgH/8AHkMhKFPGAw5XUE5f7JSJ3NJlCNicVbDErU+WzohYDtqVBDblyWYuDNskGV
        BXADNlW5FKXrZH0fq4pZp/0+/7WXTyWPSCta+sUNMW2tDl0QYaRT9/hSbEoyKtc=
        =hzF9
        -----END PGP MESSAGE-----
      fp: 349CAAD68AF02E2B
  unencrypted_suffix: _unencrypted
  version: 3.13.3
