apiVersion: ENC[AES256_GCM,data:mQY=,iv:sBtmlpmTgmW8CqKCcNbB6MGgthwh8BP2qacjMKPgXa0=,tag:N1PmML32QYTjnWK0/xKYdQ==,type:str]
data:
  encryption-passphrase: ENC[AES256_GCM,data:6EzFP5alr2r077E45NITqgSIxrw+1z/5ukBtbNWY13oQbxn/Y8ddWMa0d4g=,iv:t9tb5o16w83fmRUTFrEwiad7GKM0CzITizINKZ3aKkE=,tag:VMm6/nHnNXkVCyBuIlNc/Q==,type:str]
kind: ENC[AES256_GCM,data:HBZPycuL,iv:9HzfHL5Jh3v6MbpkeXBfifv3sMvwV5Ui6uKVfaagLJ8=,tag:VJrjddNeLUD68kKq+qefrQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:IJKYYMZC+OVFysBZXL0cebO8,iv:KQMHG8+UXqysOJuf4tQ3fe4YsO/9NGh52sSwa/S4C6U=,tag:iRNyoQQ9Q+ezXE1AaU8/Xw==,type:str]
  namespace: ENC[AES256_GCM,data:uQHP1hGsCn9kkL8=,iv:M+Pho38E9rl272RpS4KXgO5jyRVde2NCFoSJYTo27Lo=,tag:r4G+ZsCT+Obybi2nBb0LLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMkJPOTNUNk5XZ1N0bzVn
        cmxWSEJCcEp1ZmFJVklpUGlGUWpRdjVMTHdrCmV6ZTR4aGpJQnFiZURxOTFWMnR3
        U2xBYzA3T0U0VWs4am04N0JiY0FrRzAKLS0tIFhkUU5Yc3R3bGozR0QxV1UwYkhk
        ZXk3TE9GNXdKTjM4ekM5UHFKSi9aRnMKPreyFuPbE9sjPKYxm0hFEGvk11pjXW6n
        6oX1KzOBWxLoozUvXby3EyH2rMn/IU4ZLrdvzZ3OkVJdprUbI5wljA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age195etzk5xvqhr7jl7chpuq355er6ajejf5uvreqgj2aara2ymj9wqvv24am
  lastmodified: "2026-09-21T08:35:13Z"
  mac: ENC[AES256_GCM,data:i9VBHo8qdW95IwxE00/hHPVG863riqVLLqtWNaloJ7HScZwrwRK1ofTjoOudc6dLeVytGI7Zn0wZLhR/9pWB0qLOQNpkyXewGbzYdSje/fi0bfTq7uyerXgm91BTUr6KQSZvu8K2yoYKQfJhPVWmrXDXmxerBeDEmLRfQckNTIw=,iv:G5P0oW/IvvLYLVkmHKIiCF66j1XT8j/aDzMUmtD2blA=,tag:BnUrrGPy+D84JP6HcZxF3A==,type:str]
  pgp:
    - created_at: "2026-09-21T08:35:13Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5SeLKJj2tCjAQ/9EByLPedfmxxekS9OEDP9+QTpJIBXDSB91mP6OYRYg6FQ
        5kHCwUTJtEdeXhdwElqpM05CE7dQxFkV1HL5T9Rdw8c0tGXLqajEJ8yvDHX7X1AV
        7XURw7JqYhfZH2YIQy5JhIdm6zOA8vUt+qpBAfl3Lo0+5LID+YpFvbZNShR7J8L1
        KcNwr8x32sPbda8/Pt0LI+tjmuRh6UOCXfEP0jwm2VJRkkoNKfrTd3O1X+mErJWw
        fC3S6mzQWJ1DT+kEmHoWpLW8Lg0uIrtRvM8bMJ8AKaVJq4xupfL24DNDn+LHxRki
        6b3xo8ZiU2xGQHcWbbydtD6CuSi7gEF13U5jCefM1fQgLuCm8JxwLO136/NCMqYS
        IfPXNe9zoNjDqxRXzps8H0mpIs0np7hpYrMhlU8nSERFyn68dCLrTOapR43U06qK
        emNeJggafivtfDOBHtmwoxxRbHMJlXrSClMUuMuPZJ1lvLsK3jWfWV039W3b9HS+
        Qnp4hlo9cnM4DiwagtV1kbCQxBCk0Ft1c03AITY/uILeRUcyxvQ6IcCjPxvv3Drd
        X/Sj4pWyNn1Ysl1c3yKxyfduY6Wei2xEFE2YRvmD2uyhj1/jhlLMT7ZI7uILa8nQ
        ZbQhvVQ3pMlu2Fx7/AgOOgYYcIs/gwDcn+Lz4ri1bLeflANDudTx3Df8HIfjzOfS
        XgHMUuH31CpWJ5tZng+4p01U/rdZzcLtOgg9cT+tftd4oPiSX+WNvhcNv7aM3Dyf
        2ygm14b65xVVvd2w0j+ELfor99Ik3WFoA4cgYsTFSPI6/MP66wCbPr+2qUQRqPE=
        =kqNF
        -----END PGP MESSAGE-----
      fp: 349CAAD68AF02E2B
  unencrypted_suffix: _unencrypted
  version: 3.13.3
