---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rbac-common
spec:
  interval: 60m

  maxHistory: 2
  driftDetection:
    mode: enabled

  chart:
    spec:
      chart: rbac-common
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    fullnameOverride: cluster
    rbac:
      create: true
      singleNamespace: false
  valuesFrom:
    - kind: Secret
      name: rbac-common-helm-values
      optional: true
